### PR TITLE
Solves the db:pull/push commands issue while using :dev role

### PR DESCRIPTION
**Pull request by mikaelengstrom**
Solves #11 and #12

### CODE REVIEW

**Comment by mikaelengstrom** [comment]
Will you merge this request?  Would be nice to install it with bundler.

**Comment by phillipsnick** [comment]
+1

**Comment by zach-adams** [comment]
+1

**Comment by slackday** [comment]
+1

**Comment by BrandonShutter** [comment]
+1

**Comment by mikaelengstrom** [comment]
Until this is merged you may use my branch instead. To do so, add the following in your Gemfile:
gem 'capistrano-wpcli', :git => 'https://github.com/mikaelengstrom/capistrano-wpcli.git',  :branch => 'master'

**Comment by callerc1** [comment]
+1

**Comment by jeffbyrnes** [comment]
:+1:

**Comment by timsamuelsson** [comment]
+1

**Comment by matt3188** [comment]
+1

**Comment by landerss0n** [comment]
+1

**Comment by jeremyzahner** [comment]
Hi there!

Since it seems that @lavmeiker is not active anymore (at least for now) we just mirrored this repo and decided to continue maintaining it.

If you don't mind, just set up your pull request with our repo and we will merge it most certainly. =)

Thanks!

https://github.com/jshmrtn/capistrano-wpcli

**Comment by jeffbyrnes** [comment]
@jeremyzahner curious; any reason why you didn’t fork this repo first, then change the name? I always find it nice to trace the lineage of something back when I first encounter it, and in this fashion, that chain is broken.

Also, any chance of perhaps convincing @lavmeiker to allow you to carry on maintaining this repo directly?

**Comment by lavmeiker** [comment]
Hey guys! I'm sorry for the delay in the response, I had notifications turned off and I didn´t know.

**Comment by jeremyzahner** [comment]
@lavmeiker Welcome back! =) So i can dop my attempt =) Still, i would gladly become a collaborator, since i use your plugin daily!

**Comment by jeffbyrnes** [comment]
@lavmeiker @jeremyzahner love that I could help sync everybody up & prevent unneeded fragmentation/confusion for future visitors. Thanks all!

**Pull request merged**
